import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/issue_model.dart';

/// ---------------------------------------------------------------------------
/// ISSUE FIRESTORE SERVICE
/// ---------------------------------------------------------------------------
/// Handles all communication with the 'issues' collection in Firestore.
/// Provides real-time streams and data mutation methods.
class IssueService {
  // Reference to the 'issues' collection in Firestore
  final CollectionReference _issuesCollection =
  FirebaseFirestore.instance.collection('issues');

  /// Streams all issues from Firestore, ordered by most recent first.
  /// Converts Firestore QuerySnapshots into a List of [IssueModel] objects.
  Stream<List<IssueModel>> getIssuesStream() {
    return _issuesCollection
        .orderBy('createdAt', descending: true)
        .snapshots()
        .map((snapshot) {
      // Convert each document in the snapshot into an IssueModel
      return snapshot.docs.map((doc) => IssueModel.fromFirestore(doc)).toList();
    });
  }

  /// Updates the vote count for a specific issue in Firestore.
  /// Uses [FieldValue.increment] to ensure the operation is atomic (prevents data race).
  /// [issueId] is the document ID, [isUpvote] determines which counter to bump.
  Future<void> updateVotes(String issueId, bool isUpvote) async {
    try {
      await _issuesCollection.doc(issueId).update({
        isUpvote ? 'upvotes' : 'downvotes': FieldValue.increment(1),
      });
    } catch (e) {
      // Useful for debugging if permissions or connectivity fail
      print("Error updating votes: $e");
      rethrow;
    }
  }

  /// Adds a new issue to the Firestore collection.
  /// [newIssue] is a Map generated by the IssueModel.toMap() method.
  Future<DocumentReference> reportIssue(Map<String, dynamic> issueData) {
    return _issuesCollection.add(issueData);
  }
}